Первое ревью спринт 10
Bo4oN/java-filmorate pull request #6
Opened 2023-08-14 10:12 UTC by Bo4oN

2023-08-15 05:47 UTC, VadimZharkov commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryStorage.java
> +    private final HashMap<Integer, T> films = new HashMap<>();
Нет, класс на то и общий, чтобы не было никаких упоминаний и зависимостей от User и Film.
Нужна одна мапа и один счетчик идентификаторов. 
По идее любой класс занаследованный от Entity может быть параметром класса.
Поэтому все эти if (data.getClass() == Film.class) проверки нивелируют смысл дженерика (обобщенного или параметризированного класса) и их нужно убрать.

2023-08-15 05:48 UTC, VadimZharkov requested changes
Над дженериком нужно еще поработать.

2023-08-15 08:29 UTC, Bo4oN commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryStorage.java
> +    private final HashMap<Integer, T> films = new HashMap<>();
С общим счетчиком ID не пройду проверку в постмане. Одинаковый ID может быть у фильма и юзера (если счетчик общий то ID не могут совпадать. А так же хранить в одном месте и фильмы и пользователей кажется не логичным, при методе получения всех фильмов или всех пользователей все равно придется идти по всему списку и проверять классы.

2023-08-16 06:13 UTC, VadimZharkov approved these changes

2023-09-14 08:37 UTC, merged